<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان', 'iso_code' => 'AF', 'phone_code' => '93'],
            ['name_en' => 'Albania', 'name_ar' => 'ألبانيا', 'iso_code' => 'AL', 'phone_code' => '355'],
            ['name_en' => 'Algeria', 'name_ar' => 'الجزائر', 'iso_code' => 'DZ', 'phone_code' => '213'],
            ['name_en' => 'Andorra', 'name_ar' => 'أندورا', 'iso_code' => 'AD', 'phone_code' => '376'],
            ['name_en' => 'Angola', 'name_ar' => 'أنغولا', 'iso_code' => 'AO', 'phone_code' => '244'],
            ['name_en' => 'Antigua and Barbuda', 'name_ar' => 'أنتيغوا وباربودا', 'iso_code' => 'AG', 'phone_code' => '1-268'],
            ['name_en' => 'Argentina', 'name_ar' => 'الأرجنتين', 'iso_code' => 'AR', 'phone_code' => '54'],
            ['name_en' => 'Armenia', 'name_ar' => 'أرمينيا', 'iso_code' => 'AM', 'phone_code' => '374'],
            ['name_en' => 'Australia', 'name_ar' => 'أستراليا', 'iso_code' => 'AU', 'phone_code' => '61'],
            ['name_en' => 'Austria', 'name_ar' => 'النمسا', 'iso_code' => 'AT', 'phone_code' => '43'],
            ['name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان', 'iso_code' => 'AZ', 'phone_code' => '994'],
            ['name_en' => 'Bahamas', 'name_ar' => 'الباهاما', 'iso_code' => 'BS', 'phone_code' => '1-242'],
            ['name_en' => 'Bahrain', 'name_ar' => 'البحرين', 'iso_code' => 'BH', 'phone_code' => '973'],
            ['name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش', 'iso_code' => 'BD', 'phone_code' => '880'],
            ['name_en' => 'Barbados', 'name_ar' => 'باربادوس', 'iso_code' => 'BB', 'phone_code' => '1-246'],
            ['name_en' => 'Belarus', 'name_ar' => 'روسيا البيضاء', 'iso_code' => 'BY', 'phone_code' => '375'],
            ['name_en' => 'Belgium', 'name_ar' => 'بلجيكا', 'iso_code' => 'BE', 'phone_code' => '32'],
            ['name_en' => 'Belize', 'name_ar' => 'بليز', 'iso_code' => 'BZ', 'phone_code' => '501'],
            ['name_en' => 'Benin', 'name_ar' => 'بنين', 'iso_code' => 'BJ', 'phone_code' => '229'],
            ['name_en' => 'Bhutan', 'name_ar' => 'بوتان', 'iso_code' => 'BT', 'phone_code' => '975'],
            ['name_en' => 'Bolivia', 'name_ar' => 'بوليفيا', 'iso_code' => 'BO', 'phone_code' => '591'],
            ['name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك', 'iso_code' => 'BA', 'phone_code' => '387'],
            ['name_en' => 'Botswana', 'name_ar' => 'بوتسوانا', 'iso_code' => 'BW', 'phone_code' => '267'],
            ['name_en' => 'Brazil', 'name_ar' => 'البرازيل', 'iso_code' => 'BR', 'phone_code' => '55'],
            ['name_en' => 'Brunei', 'name_ar' => 'بروناي', 'iso_code' => 'BN', 'phone_code' => '673'],
            ['name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا', 'iso_code' => 'BG', 'phone_code' => '359'],
            ['name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو', 'iso_code' => 'BF', 'phone_code' => '226'],
            ['name_en' => 'Burundi', 'name_ar' => 'بوروندي', 'iso_code' => 'BI', 'phone_code' => '257'],
            ['name_en' => 'Cabo Verde', 'name_ar' => 'الرأس الأخضر', 'iso_code' => 'CV', 'phone_code' => '238'],
            ['name_en' => 'Cambodia', 'name_ar' => 'كمبوديا', 'iso_code' => 'KH', 'phone_code' => '855'],
            ['name_en' => 'Cameroon', 'name_ar' => 'الكاميرون', 'iso_code' => 'CM', 'phone_code' => '237'],
            ['name_en' => 'Canada', 'name_ar' => 'كندا', 'iso_code' => 'CA', 'phone_code' => '1'],
            ['name_en' => 'Central African Republic', 'name_ar' => 'جمهورية أفريقيا الوسطى', 'iso_code' => 'CF', 'phone_code' => '236'],
            ['name_en' => 'Chad', 'name_ar' => 'تشاد', 'iso_code' => 'TD', 'phone_code' => '235'],
            ['name_en' => 'Chile', 'name_ar' => 'تشيلي', 'iso_code' => 'CL', 'phone_code' => '56'],
            ['name_en' => 'China', 'name_ar' => 'الصين', 'iso_code' => 'CN', 'phone_code' => '86'],
            ['name_en' => 'Colombia', 'name_ar' => 'كولومبيا', 'iso_code' => 'CO', 'phone_code' => '57'],
            ['name_en' => 'Comoros', 'name_ar' => 'جزر القمر', 'iso_code' => 'KM', 'phone_code' => '269'],
            ['name_en' => 'Congo, Democratic Republic of the', 'name_ar' => 'جمهورية الكونغو الديمقراطية', 'iso_code' => 'CD', 'phone_code' => '243'],
            ['name_en' => 'Congo, Republic of the', 'name_ar' => 'جمهورية الكونغو', 'iso_code' => 'CG', 'phone_code' => '242'],
            ['name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا', 'iso_code' => 'CR', 'phone_code' => '506'],
            ['name_en' => 'Croatia', 'name_ar' => 'كرواتيا', 'iso_code' => 'HR', 'phone_code' => '385'],
            ['name_en' => 'Cuba', 'name_ar' => 'كوبا', 'iso_code' => 'CU', 'phone_code' => '53'],
            ['name_en' => 'Cyprus', 'name_ar' => 'قبرص', 'iso_code' => 'CY', 'phone_code' => '357'],
            ['name_en' => 'Czech Republic', 'name_ar' => 'الجمهورية التشيكية', 'iso_code' => 'CZ', 'phone_code' => '420'],
            ['name_en' => 'Denmark', 'name_ar' => 'الدنمارك', 'iso_code' => 'DK', 'phone_code' => '45'],
            ['name_en' => 'Djibouti', 'name_ar' => 'جيبوتي', 'iso_code' => 'DJ', 'phone_code' => '253'],
            ['name_en' => 'Dominica', 'name_ar' => 'دومينيكا', 'iso_code' => 'DM', 'phone_code' => '1-767'],
            ['name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية الدومينيكان', 'iso_code' => 'DO', 'phone_code' => '1-809'],
            ['name_en' => 'Ecuador', 'name_ar' => 'الإكوادور', 'iso_code' => 'EC', 'phone_code' => '593'],
            ['name_en' => 'Egypt', 'name_ar' => 'مصر', 'iso_code' => 'EG', 'phone_code' => '20'],
            ['name_en' => 'El Salvador', 'name_ar' => 'السلفادور', 'iso_code' => 'SV', 'phone_code' => '503'],
            ['name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائية', 'iso_code' => 'GQ', 'phone_code' => '240'],
            ['name_en' => 'Eritrea', 'name_ar' => 'إريتريا', 'iso_code' => 'ER', 'phone_code' => '291'],
            ['name_en' => 'Estonia', 'name_ar' => 'إستونيا', 'iso_code' => 'EE', 'phone_code' => '372'],
            ['name_en' => 'Eswatini', 'name_ar' => 'إسواتيني', 'iso_code' => 'SZ', 'phone_code' => '268'],
            ['name_en' => 'Ethiopia', 'name_ar' => 'إثيوبيا', 'iso_code' => 'ET', 'phone_code' => '251'],
            ['name_en' => 'Fiji', 'name_ar' => 'فيجي', 'iso_code' => 'FJ', 'phone_code' => '679'],
            ['name_en' => 'Finland', 'name_ar' => 'فنلندا', 'iso_code' => 'FI', 'phone_code' => '358'],
            ['name_en' => 'France', 'name_ar' => 'فرنسا', 'iso_code' => 'FR', 'phone_code' => '33'],
            ['name_en' => 'Gabon', 'name_ar' => 'الغابون', 'iso_code' => 'GA', 'phone_code' => '241'],
            ['name_en' => 'Gambia', 'name_ar' => 'غامبيا', 'iso_code' => 'GM', 'phone_code' => '220'],
            ['name_en' => 'Georgia', 'name_ar' => 'جورجيا', 'iso_code' => 'GE', 'phone_code' => '995'],
            ['name_en' => 'Germany', 'name_ar' => 'ألمانيا', 'iso_code' => 'DE', 'phone_code' => '49'],
            ['name_en' => 'Ghana', 'name_ar' => 'غانا', 'iso_code' => 'GH', 'phone_code' => '233'],
            ['name_en' => 'Greece', 'name_ar' => 'اليونان', 'iso_code' => 'GR', 'phone_code' => '30'],
            ['name_en' => 'Grenada', 'name_ar' => 'غرينادا', 'iso_code' => 'GD', 'phone_code' => '1-473'],
            ['name_en' => 'Guatemala', 'name_ar' => 'غواتيمالا', 'iso_code' => 'GT', 'phone_code' => '502'],
            ['name_en' => 'Guinea', 'name_ar' => 'غينيا', 'iso_code' => 'GN', 'phone_code' => '224'],
            ['name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا بيساو', 'iso_code' => 'GW', 'phone_code' => '245'],
            ['name_en' => 'Guyana', 'name_ar' => 'غيانا', 'iso_code' => 'GY', 'phone_code' => '592'],
            ['name_en' => 'Haiti', 'name_ar' => 'هايتي', 'iso_code' => 'HT', 'phone_code' => '509'],
            ['name_en' => 'Honduras', 'name_ar' => 'هندوراس', 'iso_code' => 'HN', 'phone_code' => '504'],
            ['name_en' => 'Hungary', 'name_ar' => 'المجر', 'iso_code' => 'HU', 'phone_code' => '36'],
            ['name_en' => 'Iceland', 'name_ar' => 'أيسلندا', 'iso_code' => 'IS', 'phone_code' => '354'],
            ['name_en' => 'India', 'name_ar' => 'الهند', 'iso_code' => 'IN', 'phone_code' => '91'],
            ['name_en' => 'Indonesia', 'name_ar' => 'إندونيسيا', 'iso_code' => 'ID', 'phone_code' => '62'],
            ['name_en' => 'Iran', 'name_ar' => 'إيران', 'iso_code' => 'IR', 'phone_code' => '98'],
            ['name_en' => 'Iraq', 'name_ar' => 'العراق', 'iso_code' => 'IQ', 'phone_code' => '964'],
            ['name_en' => 'Ireland', 'name_ar' => 'أيرلندا', 'iso_code' => 'IE', 'phone_code' => '353'],
            ['name_en' => 'Israel', 'name_ar' => 'إسرائيل', 'iso_code' => 'IL', 'phone_code' => '972'],
            ['name_en' => 'Italy', 'name_ar' => 'إيطاليا', 'iso_code' => 'IT', 'phone_code' => '39'],
            ['name_en' => 'Jamaica', 'name_ar' => 'جامايكا', 'iso_code' => 'JM', 'phone_code' => '1-876'],
            ['name_en' => 'Japan', 'name_ar' => 'اليابان', 'iso_code' => 'JP', 'phone_code' => '81'],
            ['name_en' => 'Jordan', 'name_ar' => 'الأردن', 'iso_code' => 'JO', 'phone_code' => '962'],
            ['name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان', 'iso_code' => 'KZ', 'phone_code' => '7'],
            ['name_en' => 'Kenya', 'name_ar' => 'كينيا', 'iso_code' => 'KE', 'phone_code' => '254'],
            ['name_en' => 'Kiribati', 'name_ar' => 'كيريباس', 'iso_code' => 'KI', 'phone_code' => '686'],
            ['name_en' => 'Kuwait', 'name_ar' => 'الكويت', 'iso_code' => 'KW', 'phone_code' => '965'],
            ['name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان', 'iso_code' => 'KG', 'phone_code' => '996'],
            ['name_en' => 'Laos', 'name_ar' => 'لاوس', 'iso_code' => 'LA', 'phone_code' => '856'],
            ['name_en' => 'Latvia', 'name_ar' => 'لاتفيا', 'iso_code' => 'LV', 'phone_code' => '371'],
            ['name_en' => 'Lebanon', 'name_ar' => 'لبنان', 'iso_code' => 'LB', 'phone_code' => '961'],
            ['name_en' => 'Lesotho', 'name_ar' => 'ليسوتو', 'iso_code' => 'LS', 'phone_code' => '266'],
            ['name_en' => 'Liberia', 'name_ar' => 'ليبيريا', 'iso_code' => 'LR', 'phone_code' => '231'],
            ['name_en' => 'Libya', 'name_ar' => 'ليبيا', 'iso_code' => 'LY', 'phone_code' => '218'],
            ['name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين', 'iso_code' => 'LI', 'phone_code' => '423'],
            ['name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا', 'iso_code' => 'LT', 'phone_code' => '370'],
            ['name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ', 'iso_code' => 'LU', 'phone_code' => '352'],
            ['name_en' => 'Madagascar', 'name_ar' => 'مدغشقر', 'iso_code' => 'MG', 'phone_code' => '261'],
            ['name_en' => 'Malawi', 'name_ar' => 'مالاوي', 'iso_code' => 'MW', 'phone_code' => '265'],
            ['name_en' => 'Malaysia', 'name_ar' => 'ماليزيا', 'iso_code' => 'MY', 'phone_code' => '60'],
            ['name_en' => 'Maldives', 'name_ar' => 'جزر المالديف', 'iso_code' => 'MV', 'phone_code' => '960'],
            ['name_en' => 'Mali', 'name_ar' => 'مالي', 'iso_code' => 'ML', 'phone_code' => '223'],
            ['name_en' => 'Malta', 'name_ar' => 'مالطا', 'iso_code' => 'MT', 'phone_code' => '356'],
            ['name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', 'iso_code' => 'MH', 'phone_code' => '692'],
            ['name_en' => 'Mauritania', 'name_ar' => 'موريتانيا', 'iso_code' => 'MR', 'phone_code' => '222'],
            ['name_en' => 'Mauritius', 'name_ar' => 'موريشيوس', 'iso_code' => 'MU', 'phone_code' => '230'],
            ['name_en' => 'Mexico', 'name_ar' => 'المكسيك', 'iso_code' => 'MX', 'phone_code' => '52'],
            ['name_en' => 'Micronesia', 'name_ar' => 'ولايات ميكرونيسيا المتحدة', 'iso_code' => 'FM', 'phone_code' => '691'],
            ['name_en' => 'Moldova', 'name_ar' => 'مولدوفا', 'iso_code' => 'MD', 'phone_code' => '373'],
            ['name_en' => 'Monaco', 'name_ar' => 'موناكو', 'iso_code' => 'MC', 'phone_code' => '377'],
            ['name_en' => 'Mongolia', 'name_ar' => 'منغوليا', 'iso_code' => 'MN', 'phone_code' => '976'],
            ['name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود', 'iso_code' => 'ME', 'phone_code' => '382'],
            ['name_en' => 'Morocco', 'name_ar' => 'المغرب', 'iso_code' => 'MA', 'phone_code' => '212'],
            ['name_en' => 'Mozambique', 'name_ar' => 'موزمبيق', 'iso_code' => 'MZ', 'phone_code' => '258'],
            ['name_en' => 'Myanmar', 'name_ar' => 'ميانمار', 'iso_code' => 'MM', 'phone_code' => '95'],
            ['name_en' => 'Namibia', 'name_ar' => 'ناميبيا', 'iso_code' => 'NA', 'phone_code' => '264'],
            ['name_en' => 'Nauru', 'name_ar' => 'ناورو', 'iso_code' => 'NR', 'phone_code' => '674'],
            ['name_en' => 'Nepal', 'name_ar' => 'نيبال', 'iso_code' => 'NP', 'phone_code' => '977'],
            ['name_en' => 'Netherlands', 'name_ar' => 'هولندا', 'iso_code' => 'NL', 'phone_code' => '31'],
            ['name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا', 'iso_code' => 'NZ', 'phone_code' => '64'],
            ['name_en' => 'Nicaragua', 'name_ar' => 'نيكاراغوا', 'iso_code' => 'NI', 'phone_code' => '505'],
            ['name_en' => 'Niger', 'name_ar' => 'النيجر', 'iso_code' => 'NE', 'phone_code' => '227'],
            ['name_en' => 'Nigeria', 'name_ar' => 'نيجيريا', 'iso_code' => 'NG', 'phone_code' => '234'],
            ['name_en' => 'North Korea', 'name_ar' => 'كوريا الشمالية', 'iso_code' => 'KP', 'phone_code' => '850'],
            ['name_en' => 'North Macedonia', 'name_ar' => 'مقدونيا الشمالية', 'iso_code' => 'MK', 'phone_code' => '389'],
            ['name_en' => 'Norway', 'name_ar' => 'النرويج', 'iso_code' => 'NO', 'phone_code' => '47'],
            ['name_en' => 'Oman', 'name_ar' => 'عمان', 'iso_code' => 'OM', 'phone_code' => '968'],
            ['name_en' => 'Pakistan', 'name_ar' => 'باكستان', 'iso_code' => 'PK', 'phone_code' => '92'],
            ['name_en' => 'Palau', 'name_ar' => 'بالاو', 'iso_code' => 'PW', 'phone_code' => '680'],
            ['name_en' => 'Palestine', 'name_ar' => 'فلسطين', 'iso_code' => 'PS', 'phone_code' => '970'],
            ['name_en' => 'Panama', 'name_ar' => 'بنما', 'iso_code' => 'PA', 'phone_code' => '507'],
            ['name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', 'iso_code' => 'PG', 'phone_code' => '675'],
            ['name_en' => 'Paraguay', 'name_ar' => 'باراغواي', 'iso_code' => 'PY', 'phone_code' => '595'],
            ['name_en' => 'Peru', 'name_ar' => 'بيرو', 'iso_code' => 'PE', 'phone_code' => '51'],
            ['name_en' => 'Philippines', 'name_ar' => 'الفلبين', 'iso_code' => 'PH', 'phone_code' => '63'],
            ['name_en' => 'Poland', 'name_ar' => 'بولندا', 'iso_code' => 'PL', 'phone_code' => '48'],
            ['name_en' => 'Portugal', 'name_ar' => 'البرتغال', 'iso_code' => 'PT', 'phone_code' => '351'],
            ['name_en' => 'Qatar', 'name_ar' => 'قطر', 'iso_code' => 'QA', 'phone_code' => '974'],
            ['name_en' => 'Romania', 'name_ar' => 'رومانيا', 'iso_code' => 'RO', 'phone_code' => '40'],
            ['name_en' => 'Russia', 'name_ar' => 'روسيا', 'iso_code' => 'RU', 'phone_code' => '7'],
            ['name_en' => 'Rwanda', 'name_ar' => 'رواندا', 'iso_code' => 'RW', 'phone_code' => '250'],
            ['name_en' => 'Saint Kitts and Nevis', 'name_ar' => 'سانت كيتس ونيفيس', 'iso_code' => 'KN', 'phone_code' => '1-869'],
            ['name_en' => 'Saint Lucia', 'name_ar' => 'سانت لوسيا', 'iso_code' => 'LC', 'phone_code' => '1-758'],
            ['name_en' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سانت فنسنت وجزر غرينادين', 'iso_code' => 'VC', 'phone_code' => '1-784'],
            ['name_en' => 'Samoa', 'name_ar' => 'ساموا', 'iso_code' => 'WS', 'phone_code' => '685'],
            ['name_en' => 'San Marino', 'name_ar' => 'سان مارينو', 'iso_code' => 'SM', 'phone_code' => '378'],
            ['name_en' => 'Sao Tome and Principe', 'name_ar' => 'ساو تومي وبرينسيبي', 'iso_code' => 'ST', 'phone_code' => '239'],
            ['name_en' => 'Saudi Arabia', 'name_ar' => 'المملكة العربية السعودية', 'iso_code' => 'SA', 'phone_code' => '966'],
            ['name_en' => 'Senegal', 'name_ar' => 'السنغال', 'iso_code' => 'SN', 'phone_code' => '221'],
            ['name_en' => 'Serbia', 'name_ar' => 'صربيا', 'iso_code' => 'RS', 'phone_code' => '381'],
            ['name_en' => 'Seychelles', 'name_ar' => 'سيشيل', 'iso_code' => 'SC', 'phone_code' => '248'],
            ['name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون', 'iso_code' => 'SL', 'phone_code' => '232'],
            ['name_en' => 'Singapore', 'name_ar' => 'سنغافورة', 'iso_code' => 'SG', 'phone_code' => '65'],
            ['name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا', 'iso_code' => 'SK', 'phone_code' => '421'],
            ['name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا', 'iso_code' => 'SI', 'phone_code' => '386'],
            ['name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان', 'iso_code' => 'SB', 'phone_code' => '677'],
            ['name_en' => 'Somalia', 'name_ar' => 'الصومال', 'iso_code' => 'SO', 'phone_code' => '252'],
            ['name_en' => 'South Africa', 'name_ar' => 'جنوب أفريقيا', 'iso_code' => 'ZA', 'phone_code' => '27'],
            ['name_en' => 'South Korea', 'name_ar' => 'كوريا الجنوبية', 'iso_code' => 'KR', 'phone_code' => '82'],
            ['name_en' => 'South Sudan', 'name_ar' => 'جنوب السودان', 'iso_code' => 'SS', 'phone_code' => '211'],
            ['name_en' => 'Spain', 'name_ar' => 'إسبانيا', 'iso_code' => 'ES', 'phone_code' => '34'],
            ['name_en' => 'Sri Lanka', 'name_ar' => 'سريلانكا', 'iso_code' => 'LK', 'phone_code' => '94'],
            ['name_en' => 'Sudan', 'name_ar' => 'السودان', 'iso_code' => 'SD', 'phone_code' => '249'],
            ['name_en' => 'Suriname', 'name_ar' => 'سورينام', 'iso_code' => 'SR', 'phone_code' => '597'],
            ['name_en' => 'Sweden', 'name_ar' => 'السويد', 'iso_code' => 'SE', 'phone_code' => '46'],
            ['name_en' => 'Switzerland', 'name_ar' => 'سويسرا', 'iso_code' => 'CH', 'phone_code' => '41'],
            ['name_en' => 'Syria', 'name_ar' => 'سوريا', 'iso_code' => 'SY', 'phone_code' => '963'],
            ['name_en' => 'Taiwan', 'name_ar' => 'تايوان', 'iso_code' => 'TW', 'phone_code' => '886'],
            ['name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان', 'iso_code' => 'TJ', 'phone_code' => '992'],
            ['name_en' => 'Tanzania', 'name_ar' => 'تنزانيا', 'iso_code' => 'TZ', 'phone_code' => '255'],
            ['name_en' => 'Thailand', 'name_ar' => 'تايلاند', 'iso_code' => 'TH', 'phone_code' => '66'],
            ['name_en' => 'Timor-Leste', 'name_ar' => 'تيمور الشرقية', 'iso_code' => 'TL', 'phone_code' => '670'],
            ['name_en' => 'Togo', 'name_ar' => 'توغو', 'iso_code' => 'TG', 'phone_code' => '228'],
            ['name_en' => 'Tonga', 'name_ar' => 'تونغا', 'iso_code' => 'TO', 'phone_code' => '676'],
            ['name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينيداد وتوباغو', 'iso_code' => 'TT', 'phone_code' => '1-868'],
            ['name_en' => 'Tunisia', 'name_ar' => 'تونس', 'iso_code' => 'TN', 'phone_code' => '216'],
            ['name_en' => 'Turkey', 'name_ar' => 'تركيا', 'iso_code' => 'TR', 'phone_code' => '90'],
            ['name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان', 'iso_code' => 'TM', 'phone_code' => '993'],
            ['name_en' => 'Tuvalu', 'name_ar' => 'توفالو', 'iso_code' => 'TV', 'phone_code' => '688'],
            ['name_en' => 'Uganda', 'name_ar' => 'أوغندا', 'iso_code' => 'UG', 'phone_code' => '256'],
            ['name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا', 'iso_code' => 'UA', 'phone_code' => '380'],
            ['name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة', 'iso_code' => 'AE', 'phone_code' => '971'],
            ['name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة', 'iso_code' => 'GB', 'phone_code' => '44'],
            ['name_en' => 'United States of America', 'name_ar' => 'الولايات المتحدة الأمريكية', 'iso_code' => 'US', 'phone_code' => '1'],
            ['name_en' => 'Uruguay', 'name_ar' => 'أوروغواي', 'iso_code' => 'UY', 'phone_code' => '598'],
            ['name_en' => 'Uzbekistan', 'name_ar' => 'أوزبكستان', 'iso_code' => 'UZ', 'phone_code' => '998'],
            ['name_en' => 'Vanuatu', 'name_ar' => 'فانواتو', 'iso_code' => 'VU', 'phone_code' => '678'],
            ['name_en' => 'Venezuela', 'name_ar' => 'فنزويلا', 'iso_code' => 'VE', 'phone_code' => '58'],
            ['name_en' => 'Vietnam', 'name_ar' => 'فيتنام', 'iso_code' => 'VN', 'phone_code' => '84'],
            ['name_en' => 'Yemen', 'name_ar' => 'اليمن', 'iso_code' => 'YE', 'phone_code' => '967'],
            ['name_en' => 'Zambia', 'name_ar' => 'زامبيا', 'iso_code' => 'ZM', 'phone_code' => '260'],
            ['name_en' => 'Zimbabwe', 'name_ar' => 'زيمبابوي', 'iso_code' => 'ZW', 'phone_code' => '263'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
